apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: "<YOUR STORAGE ACCOUNT>"
  - name: accountKey
    value: "<YOUR STORAGE ACCOUNT ACCESS KEY>"
  - name: tableName
    value: "state"